name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.11.0"
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "macOS 14.0"
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run `buddy search --species dragon`
        2. See error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant output
      description: Please copy and paste any relevant output
      render: shell
